stages:
   - deploy
deploy:
   stage: deploy
   script:
      - whoami
      - git config --global --add safe.directory /var/www/html/duolingo/public_html/ihc_duolingovr
      - echo "Deploying to production server"
      - cd $home
      - cd ..
      - pwd
      - cd $WORK_DIR
      - pwd
      - git pull
   after_script:
      - echo "Done"