stages:
   - deploy
deploy:
   stage: deploy
   script:
      - whoami
      - echo "Deploying to production server"
      - cd $home
      - cd ..
      - pwd
      - cd /var/www/html/duolingo/public_html/ihc_duolingovr/
      - pwd
      - git pull
      - systemctl restart apache2
      - systemctl reload apache2
   after_script:
      - echo "Done"