stages:
   - deploy
deploy:
   stage: deploy

   script:
      - echo "Deploying to production server"
      - cd $home
      - pwd
      - cd $WORK_DIR && git pull
   after_script:
      - echo "Done"