stages:
   - deploy
deploy:
   image: ubuntu:latest
   stage: deploy
   before_script:
      - apt-get -yqq update
      - apt-get -yqq install ssh
      - install -m 600 -D /dev/null ~/.ssh/id_rsa
      - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_rsa
      - mkdir -p ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "Deploying to $SSH_HOST"
   script:
      - echo "Deploying to production server"
      - ssh $SSH_USER@$SSH_HOST "cd $SSH_PATH && git pull"
   after_script:
      - echo "Done"
      - rm -rf ~/.ssh