stages:
   - deploy
deploy:
   stage: deploy

   script:
      - echo "Deploying to production server"
      - cd $home
      - cd ..
      - pwd
      - cd /var/www/html/duolingo/public_html/ihc_duolingovr/
      - pwd
      - git pull
   after_script:
      - echo "Done"