stages:
   - deploy
deploy:
   stage: deploy

   script:
      - echo "Deploying to production server"
      - cd $home
      - cd ..
      - pwd
      - cd $WORK_DIR
      - pwd
      - git pull
   after_script:
      - echo "Done"